# Default config for Vagrant
#
# Don't change this; use vagrantconfig_local.yaml to override these settings
# instead.

nfs: true
gui: false
ip_address: 192.168.10.55
memory_size: 1024
number_cpus: 2
box: "hashicorp/precise32"
package_name: "kuma-ubuntu.box"
mount_point: "/home/vagrant/src"
